specVersion: 1.0.0
name: frontier-evm-starter-project
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=0.35.0'
  query:
    name: '@subql/query'
    version: '>=0.16.0'
description: >-
  A basic Frontier EVM example project with an event and call handler. Read more
  about this at https://doc.subquery.network/create/frontier/
repository: https://github.com/subquery/tutorials-frontier-evm-starter
schema:
  file: ./schema.graphql
network:
  chainId: '0xddb89973361a170839f80f152d2e9e38a376a5a7eccefcade763f46a8e567019'
  endpoint: wss://rpc.shibuya.astar.network
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 1440000
    processor:
      file: ./node_modules/@subql/contract-processors/dist/frontierEvm.js
      options:
        abi: erc20
        address: '0x26465200f3Fa0ac4f48a46FBfc663596eb9D6C6B'
    assets:
      erc20:
        file: ./erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleFrontierEvmEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
        - handler: handleFrontierEvmCall
          kind: substrate/FrontierEvmCall
          filter:
            function: approve(address to,uint256 value)
